export const skillsConfig = [
  "Acquiring Skills",
  "Acrobatics",
  "Aid Another",
  "Appraise",
  "Bluff",
  "Climb",
  "Craft",
  "Diplomacy",
  'Disable Device',
  "Disguise",
  "Escape Artist",
  "Fly",
  "Handle Animal",
  "Heal",
  "Intimidate",
  "Knowledge",
  "Linguistics",
  "Perception",
  "Perform",
  "Profession",
  "Ride",
  "Sense Motive",
  "Skill Checks",
  "Sleight of Hand",
  "Spellcraft",
  "Stealth",
  "Survival",
  'Swim'
]